# Dockerfile.dev
FROM node:20-alpine

WORKDIR /app

# Установка зависимостей
COPY package*.json ./
RUN npm install

# Копируем Prisma схему
COPY prisma ./prisma/

# Генерируем Prisma Client
RUN npx prisma generate

# Копируем остальные файлы
COPY . .

EXPOSE 3000

# Для разработки используем nodemon через npm run start:dev
CMD ["npm", "run", "start:dev"]